//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerLocations.Business.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string country { get; set; }
    }
}
