//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerLocations.Business.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int location_number { get; set; }
        public string country { get; set; }
        public string prefix { get; set; }
        public string ph_number { get; set; }
        public string timespane { get; set; }
        public bool loc_enabled { get; set; }
    }
}
